### PR TITLE
Redundant calls of java.lang.Class methods.

### PR DESCRIPTION
**Pull request by arturobernalg**
Remove redundant calls of java.lang.Class methods. Replaced with object instanceof

### CODE REVIEW

**Review by lukaszlenart — COMMENTED** [review]
Why do you think `instanceof` is better than `<Class>.class.isInstance`?

**Comment by arturobernalg** [comment]
HI @lukaszlenart 
I think we don't need check dynamic if are assignment-compatible. IMO `isInstance` should be use when are using reflection. Off course this can be subjective :)
TY

**Review by lukaszlenart — APPROVED** [review]
LGTM 👍

**Review by jochenw — COMMENTED** [review]
I'll admit, that the version with instanceof looks better, and is more readable. Two things, though:

- Do you have a pointer, that "instanceof" is actually better, that using class.isInstance? (I can well imagine, that both are the same, internally.
- I am repeating myself again, and again here: 25 files changed in one go? Are you kidding me?

Thanks, Jochen

**Comment by arturobernalg** [comment]
Hi @jochenw 
I don't think "instanceof" it's better. IMO they should use in different way. "Determines if the specified Object is assignment-compatible with the object represented by this Class. This method is the dynamic equivalent of the Java language instanceof operator. "

Regarding with the numbers of file, I´m trying to create small PR, but in sometimes its difficult split the PR and been coherent with the change
TY

**Comment by lukaszlenart** [comment]
> * I am repeating myself again, and again here: 25 files changed in one go? Are you kidding me?

I'm fine with having all the same changes as a one commit - in this case changes to all the files are related to the same thing

**Pull request merged**
