### PR TITLE
enhance MethodPermCacheTest

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
@garydgregory

**Comment by sullis** [comment]
@garydgregory

**Comment by garydgregory** [comment]
I'd prefer for someone who has worked on this part of the project before to take a look.

**Comment by sullis** [comment]
please review @simonetripodi @lukaszlenart @grobmeier

**Comment by sullis** [comment]
Ready for review.

**Comment by sullis** [comment]
this is ready for review

**Comment by lukaszlenart** [comment]
LGTM 👍

**Pull request merged**
