### PR TITLE
JUnit v4.13.1

### PR DESCRIPTION
**Pull request by nhojpatrick**
Upgrade to JUnit v4.13.1

### CODE REVIEW

**Comment by garydgregory** [comment]
Please make sure you update changes.xml.

Gary

**Comment by lukaszlenart** [comment]
Even if this is a test dependency and it won't affect users?

**Comment by garydgregory** [comment]
> Even if this is a test dependency and it won't affect users?

Absolutely IMO, some users are also developers. Consider that are two categories of "users" here: users of the APIs and contributors to the component.

**Comment by lukaszlenart** [comment]
Is there any guideline what should be included in `changes.xml`? does Maven plugins should also be included? Should I create a JIRA ticket for each?

**Comment by garydgregory** [comment]
I do not create Jira tickets for these kind of changes, I just don't see
the need. If the changes file is updated then the release notes will show
the changes, which is what matters most IMO. We do get a Jira report
generated with the site but that is different and does not end up in the
release notes.

I document all updates. Think of it as transparency, why would you hide the
update? I don't like to tell people to look at the git history when we can
provide this information as part of our workflow.

Gary

**Comment by lukaszlenart** [comment]
So this means the ultimate source of truth (changes) is `changes.xml`?

**Comment by garydgregory** [comment]
Well, yes, unless you want to go through the git history.

Gary

**Pull request merged**
